#!/bin/bash
read -p "enter device u wish to hack: " device

for i in {0..100}; do
	echo "Preparing for infultration of $device $i%"
	sleep 0.05
	if [[ $i -eq 100 ]]; then
		break
	fi
	clear
done

for i in {0..100}; do
        echo "Beging to retrive information from $device $i%"
        sleep 0.01
        if [[ $i -eq 100 ]]; then
                break
        fi
        clear
done

for i in {0..100}; do
        echo "Recovery from $device $i%"
        sleep 0.05
        if [[ $i -eq 100 ]]; then
                break
        fi
        clear
done

echo "$device hacking complete"
echo "this are his information: "
ls
