# Generated by Django 4.2.11 on 2024-05-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_product_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_category_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
